config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/help'

  resources :missions
  root 'missions#index'

end

app/models/mission.rb
class Mission < ActiveRecord::Base
	validates :location, :floor, :rescue_link, :presence => true


	validate :url_should_be_url
	validate :rescued_should_be_rescued

  	def url_should_be_url
    	errors.add(:rescue_link, "Not a valid URL Please upload to imgur or cloudfront. (This is to prevent spam)") if
    		!rescue_link.index('http')  == 0 #|| !rescue_link.include?('imgur.com/' || 'cloudfront.net/') 
  	end

  	def rescued_should_be_rescued
  		if rescued_link != "" && rescued_link != nil
  			errors.add(:rescued_link, "Not a valid URL. Please upload to imgur or cloudfront. (This is to prevent spam)") if
    		!rescued_link.index('http')  == 0 # || !rescued_link.include?('imgur.com/' || 'cloudfront.net/')
  		end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]

  # GET /missions
  # GET /missions.json
  def index
    # Old code @missions = Mission.all
    @missions = Mission.order('created_at DESC').paginate(page: params[:page], per_page: 10)
    
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end

  end

  # GET /missions/1
  # GET /missions/1.json
  def show
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit

  end

  # POST /missions
  # POST /missions.json
  def create
    @mission = Mission.new(mission_params)

    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: 'Mission was successfully created.' }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1
  # PATCH/PUT /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: 'Mission was successfully updated.' }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1
  # DELETE /missions/1.json
  # There will be no deleting for now!
  #def destroy
  #  @mission.destroy
  #  respond_to do |format|
  #    format.html { redirect_to missions_url, notice: 'Mission was successfully destroyed.' }
  #    format.json { head :no_content }
  #  end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through
    def mission_params
      params.require(:mission).permit(:game, :location, :floor, :rescue_link, :rescued_link, :notes, :progress)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/missions_helper.rb
module MissionsHelper

	def check_link(link)
		if !link.nil? && !link.empty?
			"Link"
		else
			""
		end
	end

	def getStatus(label)

		if label == 2
			return "done";
		end

		if label == 1
			return "in-progress";
		end

		if label == 0
			return "";
		end
	end

	def getProgress(num)
		if num == 0
			return "Posted"
		end
		if num == 1
			return "In Progress"
		end
		if num == 2
			return "Finished"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemon Mystery Dungeon Rescue Board</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-49223760-2', 'auto');
  ga('send', 'pageview');

</script>





<body>
<div class="navbar navbar-default navbar-static-top">
  <div class="container">

    <a href="#" class="navbar-brand">Rescue Time</a>

    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav">
        <li><a href="/missions/">Rescue Board</a></li>
        <li><a href="/static_pages/about/">About</a></li>
        <li><a href="/static_pages/help/">Help</a></li>
        <li><a href="/static_pages/contact/">Contact</a></li>
      </ul>
    </div>
  </div> <!-- end container-->
</div> <!-- end container-->

  <div class="container">
    <div class="center-me well">
      <div class="container-fluid">
        <%= yield %>
      </div>
    </div>
  </div>

</body>

</html>

app/views/missions/_form.html.erb
<%= form_for(@mission) do |f| %>
  <% if @mission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</h2>

      <ul>
      <% @mission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
  <div class="field">
    <%= f.label :game %><br>
    <%= f.select :game, [['SMD','SMD'],['GTI','GTI'],['EO','EO'],['RT','RT']] %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :floor %><br>
    <%= f.number_field :floor %>
  </div>
  <div class="field">
    <%= f.label :rescue_link %><br>
    <%= f.url_field :rescue_link %>
  </div>

  <% if !@mission.new_record? %>
  <div class="field">
    <%= f.label :rescued_link %><br>
    <%= f.url_field :rescued_link %>
  </div>
  <% end %>

  <% if !@mission.rescued_link.nil? && !@mission.rescued_link.empty? %>
  <div class="field">
    <%= f.label :thank_you_link %><br>
    <%= f.url_field :thank_you_link %>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>

  <% if !@mission.new_record? %>
  <div class="field">
    <%= f.label :progress %> <br>
    <%= f.select :progress, [['Posted',0],['In Progress',1],['Finished',2]]  %>
  </div>
  <% end %>


  <div class="actions">
    <%= f.submit %>
  </div>
</div>

<script>
document.getElementById('mission_location').required = true;
document.getElementById('mission_level').required = true;
document.getElementById('mission_rescue_link').required = true;
document.getElementById('mission_rescued_link').onclick=function(){finished()};

function finished(){
  document.getElementById('mission_progress').value = 2;
}

</script>

<% end %>

app/views/missions/edit.html.erb
<h1>Editing mission</h1>

<div class="container-fluid">

<div class="form-group">
<%= render 'form' %>
</div>

<%= link_to 'Show', @mission %> |
<%= link_to 'Back', missions_path %>
</div>

app/views/missions/index.html.erb
<meta name="description" content="Rescue Time is a website to get rescued in the Pokemon Mystery Dungeon games. Pokemon Super Mystery Dungeon is the most popular game right now but it's setup to be useable all games in the series">


<!-- Makes page refresh every minute -->
<meta http-equiv="refresh" content="60">
<!-- Allows RSS to be found-->
<%= auto_discovery_link_tag :rss, missions_url(:format => :rss) %>

<div class="row">
  <h1 class="text-center">Missions</h1>
  <div class="container-responsive table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Game</th>
        <th>Location</th>
        <th>Floor</th>
        <th>Rescue</th>
        <th>Rescued</th>
        <th>Notes</th>
        <th colspan="3">Options</th>
      </tr>
    </thead>

    <tbody>
      <% @missions.each do |mission| %>
        <tr class="<%= getStatus(mission.progress)%>" >
          <td><%= mission.game %></td>
          <td><%= mission.location %></td>
          <td><%= mission.floor %></td>
          <td><a href="<%= mission.rescue_link %>"><%= check_link(mission.rescue_link) %></a></td>
          <td><a href="<%= mission.rescued_link %>"><%= check_link(mission.rescued_link) %></a></td>
          <td><%= mission.notes %></td>
          <td><%= link_to 'Show', mission %></td>
          <td><%= link_to 'Edit', edit_mission_path(mission) %></td>
          <!--<td><%= link_to 'Destroy', mission, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      <%= will_paginate @books %> 
      <i> <%= link_to 'RSS', missions_url(:format => :rss) %> </i>
      <form action="<%= new_mission_path %>">
          <input class="btn btn-primary" type="submit" value="Get Help!">
      </form>
      <br>
      <i>Page automatically refreshes every 60 seconds</i>
    </div>
  </div>
  <div class="col-md-12">
    <div class="text-center">

      <br>
      <br>
      <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/RescueDungeon" data-widget-id="683160419821858820">Tweets by @RescueDungeon</a>
    </div>
  </div>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/missions/new.html.erb
<h1>New mission</h1>

<%= render 'form' %>

<%= link_to 'Back', missions_path %>

app/views/missions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @mission.game %>
</p>

<p>
  <strong>Location:</strong>
  <%= @mission.location %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @mission.floor %>
</p>

<p>
  <strong>Rescue link:</strong>
  <a href="<%= @mission.rescue_link %>"><%= check_link(@mission.rescue_link)%></a>
</p>

<p>
  <strong>Rescued link:</strong>
  <a href="<%= @mission.rescued_link %>"><%= check_link(@mission.rescued_link) %></a>
</p>

<% if !@mission.rescued_link.nil? && !@mission.rescued_link.empty? %>
<p>
  <strong>Thank you link:</strong>
  <a href="<%= @mission.thank_you_link %>"><%= check_link(@mission.thank_you_link) %></a>
</p>
<% end %>
<p>
  <strong>Notes:</strong>
  <%= @mission.notes %>
</p>

<p>
  <strong>Progress:</strong>
  <%= getProgress(@mission.progress) %>
</p>
<script>
if (<%= @mission.progress %> == 1) {
  document.getElementsByClassName("container-fluid")[0].style.backgroundColor = "#FFD561";
} else if (<%= @mission.progress %> == 2){
  document.getElementsByClassName("container-fluid")[0].style.backgroundColor = "#61FF86";
}
</script>

<%= link_to 'Edit', edit_mission_path(@mission) %> |
<%= link_to 'Back', missions_path %>

app/views/static_pages/about.html.erb
<h2>About The Mystery Dungeon Rescue Board</h2>
<h3>Why this website was created</h3>
<p>This website was created to have one simple place for people to seek rescues and rescue others.</p><br>
<h3>About the creator<h3>
<p>This webite was created by Ray as a side project to practice my skills with Ruby on Rails, HTML, and CSS.</p>

app/views/static_pages/contact.html.erb
<h1>Contact Me</h1>
<p>If you would like to contact me for any reason at all please use the form below.</p>
<!-- Do not change the code! -->
<a id="foxyform_embed_link_731584" href="http://www.foxyform.com/">foxyform</a>
<script type="text/javascript">
(function(d, t){
   var g = d.createElement(t),
       s = d.getElementsByTagName(t)[0];
   g.src = "http://www.foxyform.com/js.php?id=731584&sec_hash=41c03ca9f2e&width=350px";
   s.parentNode.insertBefore(g, s);
}(document, "script"));
</script>
<!-- Do not change the code! -->

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>I'm not really sure what kind of help people might need. As I get more questions and suggestions I'll probably add them here.</p>

<a href="https://tt.reddit.com/r/MysteryDungeon/comments/3ts6mm/how_to_take_a_screenshot_of_rescue_mail_because/">How to Take Screenshots</a>

<h2>Want to get rescue notifications?</h2>
	<p>Either subscribe to our RSS feed with your favorite feed reader or get the pushbullet app and subscribe below.</p>
<a class="pushbullet-subscribe-widget" data-channel="rescue_time" data-widget="button" data-size="small"></a>
<script type="text/javascript">(function(){var a=document.createElement('script');a.type='text/javascript';a.async=true;a.src='https://widget.pushbullet.com/embed.js';var b=document.getElementsByTagName('script')[0];b.parentNode.insertBefore(a,b);})();</script>